# RestfulX code generation configuration options

# This option controls what the main Flex application file will be called.
# By default it will be equal to the name of your rails project camelized
project-name: soup

# This options determines what the root folder for generated Flex code is.
# By default 'app/flex'
flex-root: app/flex

# By default flex models, commands, controllers and components are genearated into
# <flex-root>/<your rails project name> folder. If you'd like to customize the target folder 
# (to say append a "com" package before your rails project name) uncomment the line below
# base-package must follow the usual flex package notation (a string separated by ".")
base-package: soup

# Main RestfulX controller is typically named AppicationController. This controller is created in 
# <base-package>.controllers folder. You can customize the name by uncommenting the following line 
# and changing the controller name.
controller-name: ApplicationController

# If you are using Rails on the back-end and Adobe AIR as the client you can generate Rails/Flex/AIR
# code to take advantage of synchronization (online/offline) support in RestfulX by changing the following
# option to true. By default distribution is disabled.
distributed: 